Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,23 +2,22 @@ name: Build and Package .ipa
 on:
   push:
   workflow_dispatch:
-
 jobs:
   build-ipa:
     runs-on: macos-latest
     steps:
       - name: Checkout repository code
         uses: actions/checkout@v4
-
+        
       - name: Select latest Xcode
         run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
-
+        
       - name: Install iOS Simulator Runtime
         run: sudo xcodebuild -downloadPlatform iOS
-
+        
       - name: Resolve SPM dependencies
         run: xcodebuild -resolvePackageDependencies -project winston.xcodeproj -scheme winston
-
+        
       - name: Build Archive
         run: |
           xcodebuild -project winston.xcodeproj \
@@ -30,8 +29,20 @@ jobs:
                CODE_SIGN_IDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGNING_ALLOWED=NO \
+               SWIFT_COMPILATION_MODE=wholemodule \
+               SWIFT_OPTIMIZATION_LEVEL="-Osize" \
                OTHER_SWIFT_FLAGS="-no-verify-emitted-module-interface" \
-               archive
+               ONLY_ACTIVE_ARCH=NO \
+               archive | tee $RUNNER_TEMP/build.log
+        continue-on-error: false
+        
+      - name: Check Archive Success
+        run: |
+          if [ ! -d "$RUNNER_TEMP/winston.xcarchive/Products/Applications/winston.app" ]; then
+            echo "Archive failed - winston.app not found"
+            cat $RUNNER_TEMP/build.log
+            exit 1
+          fi
                     
       - name: Create .ipa file
         run: |
@@ -39,7 +50,7 @@ jobs:
           cp -R $RUNNER_TEMP/winston.xcarchive/Products/Applications/winston.app $RUNNER_TEMP/Payload/winston.app
           cd $RUNNER_TEMP
           zip -r winston.ipa ./Payload
-
+          
       - name: Upload .ipa Artifact
         uses: actions/upload-artifact@v4
         with:
